#!/usr/bin/env python
import argparse
import toml
from pyompa.parse_config import run_ompa_given_toml_config_files


def main(args):
    run_ompa_given_toml_config_files(args.config_files)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("config_files", nargs="+",
     help=("Configuration file(s); multiple files will be "
           +"concatenated together"))
    main(parser.parse_args())
    
